name: Generate Datas
on:
  schedule: # execute every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:
  
jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    
    steps:
      - name: Snake Animation
        uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: alekita254
          svg_out_path: dist/github-contribution-grid-snake.svg
      
      - name: Publish to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
